# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6dfced25ea6cd6ddc8929377bc2d488ea67c53b27b19fa666c50be9291e73f1bbb26a3847741305a6ffeb3997aaebc26aa5e388be0f9d33d2dde1a17f222fe52
  
test:
  secret_key_base: 175fd551e93363afe7e2757026d869169c1c75648012e7367721f8a2ff897ece64cbdec33fbacdefb62f165f6d2d133969b8ec27c4caf770b307ad70af2d077e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
